<?php

/* Mappings de los campos y valores para mostrarlos de forma mas
amigable en los activity logs */

return [
    'field_mappings' => [
        'name' => 'Nombre',
        'last_name' => 'Apellido',
        'first_name' => 'Nombre',
        'first_surname' => 'Primer Apellido',
        'second_surname' => 'Segundo Apellido',
        'email' => 'Correo Electrónico',
        'created_at' => 'Fecha de Creación',
        'updated_at' => 'Fecha de Actualización',
        'status' => 'Estado',
        'admission_id' => 'ID de Admisión',
        'nurse_id' => 'ID de Enfermera',
        'nurse_sign' => 'Firma de Enfermera',
        'active' => 'Activo',
        'bed_id' => 'ID de Cama',
        'patient_id' => 'ID de Paciente',
        'receptionist_id' => 'ID de Recepcionista',
        'doctor_id' => 'ID de Doctor',
        'admission_dx' => 'Diagnóstico de Admisión',
        'final_dx' => 'Diagnóstico Final',
        'comment' => 'Observación',
        'discharged_date' => 'Fecha de Alta',
        'doctor_sign' => 'Firma del Doctor',
        'phone' => 'Teléfono',
        'identification_card' => 'Cédula de Identidad',
        'nationality' => 'Nacionalidad',
        'birthdate' => 'Fecha de Nacimiento',
        'position' => 'Posición',
        'marital_status' => 'Estado Civil',
        'address' => 'Dirección',
        'ars' => 'ARS',
        'diagnosis' => 'Diagnóstico',
        'diet' => 'Dieta',
        'referrals' => 'Referencias',
        'pending_studies' => 'Estudios Pendientes',
        'medication' => 'Medicación',
        'specialty' => 'Especialidad',
        'area' => 'Área',
        'exequatur' => 'Exequátur',
        'temperature' => 'Temperatura',
        'temperature_record_id' => 'ID de Registro de Temperatura',
        'eliminations' => 'Evacuaciones',
        'urinations' => 'Micciones',
        'drug' => 'Medicamento',
        'dose' => 'Dosis',
        'dose_metric' => 'Unidad de Dosis',
        'route' => 'Vía de Administración',
        'fc' => 'Frecuencia',
        'interval_in_hours' => 'Intervalo en Horas',
        'start_time' => 'Hora de Inicio',
        'suspended_at' => 'Suspendido en',
        'scheduled_time' => 'Hora Programada',
        'administered_time' => 'Hora Administrada',
        'regime' => 'Régimen',
        'room' => 'Habitación',
        'number' => 'Número de Cama',
        'description' => 'Descripción',
        'rnc' => 'RNC',
        'applied' => 'Aplicado',
    ],

    'value_mappings' => [
        'status.available' => 'Disponible',
        'status.unavailable' => 'No Disponible',
        'active.true' => 'Sí',
        'active.false' => 'No',
        'active.1' => 'Sí',
        'active.0' => 'No',
        'status.occupied' => 'Ocupada',
        'status.out_of_service' => 'Fuera de Servicio',
        'status.cleaning' => 'En Limpieza',
        'route.VO' => 'Oral',
        'route.IV' => 'Intravenosa',
        'route.IM' => 'Intramuscular',
        'route.S/C' => 'Subcutánea',
    ]
];
