<?php

return [
    'App\\Models\\User' => 'Usuario',
    'App\\Models\\Admission' => 'Ingreso',
    'App\\Models\\MedicationRecord' => 'Ficha de Medicamentos',
    'App\\Models\\NurseRecord' => 'Registro de Enfermería',
    'App\\Models\\NurseRecordDetail' => 'Evento - Registro de Enfermería',
    'App\\Models\\TemperatureRecord' => 'Hoja de Temperatura',
    'App\\Models\\MedicalOrder' => 'Orden Médica',
    'App\\Models\\MedicalOrderDetail' => 'Detalle de Orden Médica',
    'App\\Models\\Bed' => 'Cama',
    'App\\Models\\Room' => 'Habitación',
    'App\\Models\\Drug' => 'Medicamento',
    'App\\Models\\DrugDose' => 'Dosis de Medicamento',
    'App\\Models\\DrugRoute' => 'Ruta de Medicamento',
    'App\\Models\\EliminationRecord' => 'Registro de Eliminación',
    'App\\Models\\MaritalStatus' => 'Estado Civil',
    'App\\Models\\MedicationNotification' => 'Notificación de Medicamento',
    'App\\Models\\MedicationRecordDetail' => 'Detalle de Ficha de Medicamentos',
    'App\\Models\\Nationality' => 'Nacionalidad',
    'App\\Models\\Patient' => 'Paciente',
    'App\\Models\\Regime' => 'Régimen',
    'App\\Models\\TemperatureDetail' => 'Detalle de Hoja de Temperatura',
    'App\\Models\\Diet' => 'Dieta',
    'App\\Models\\Ars' => 'ARS',
    'App\\Models\\Clinic' => 'Clínica',
    'App\\Models\\ClinicArea' => 'Área de Clínica',
];
